name: Reel Automation

permissions:
  contents: write
  
on:
  workflow_dispatch:
  push:
  
jobs:
  render-and-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Stop the job if it hangs for more than 30 mins
    
    steps:
      - name: 📂 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

    

    
    


       # 🔐 IMPORTANT: Pass GitHub token to environment
      - name: 🔐 Set GitHub Token
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      

      - name: 🚀 Step 5 - Webhook & Force Push Video
        env:
          WEBHOOK_REEL: ${{ secrets.WEBHOOK_REEL }}
          WEBHOOK_VIDEO: ${{ secrets.WEBHOOK_VIDEO }}
        run: bash 5_webhook.sh
